
#if !defined(MP_GLOBAL_LEVEL_FUNCTION)
#define MP_GLOBAL_LEVEL_FUNCTION(fun)
#endif

MP_GLOBAL_LEVEL_FUNCTION(RendererInit)
MP_GLOBAL_LEVEL_FUNCTION(RendererFree)
MP_GLOBAL_LEVEL_FUNCTION(RendererEntry)

#undef MP_GLOBAL_LEVEL_FUNCTION